alias: Dryer Switch
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_boolean.dryer_switch
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.dryer_switch
            state: "on"
        sequence:
          - action: timer.start
            target:
              entity_id: timer.dryer
            data: {}
      - conditions:
          - condition: state
            entity_id: input_boolean.dryer_switch
            state: "off"
        sequence:
          - action: timer.finish
            target:
              entity_id: timer.dryer
            data: {}
mode: single
