# This is an automation for a group of tuya motion lights where when one turns on, they all turn on.
# Tuya motion lights do not allow setting between on and motion, so the set back to motion is done within the Tuya app.
# If you have fully local motion lights, add in an off and back to motion section at the end.

alias: Flood Lights Automation
description: ""
triggers:
  - type: turned_on
    device_id: 49cbd172
    entity_id: 3adcfff0
    domain: light
    trigger: device
  - type: turned_on
    device_id: ae34d2
    entity_id: 9788e
    domain: light
    trigger: device
  - type: turned_on
    device_id: bbe9
    entity_id: daf6
    domain: light
    trigger: device
conditions:
  - condition: sun
    before: sunrise
    after: sunset
actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.front_flood_lights
mode: single
